1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [2]:
import numpy as np

In [3]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [3]:
a.reshape(2,6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [4]:
a.reshape(3,4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [5]:
a.reshape(4,3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [6]:
a.reshape(6,2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [8]:
a.reshape(12, 1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [21]:
a.reshape(12, -1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [19]:
a.reshape(3, -1)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [11]:
a.reshape(2, -1)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [20]:
a.reshape(-1, 6)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [17]:
a.reshape(-1,12)

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

Нет.

5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [6]:
a = np.random.rand(3,4)
a

array([[0.69032376, 0.92725569, 0.23165573, 0.88976584],
       [0.90471173, 0.94026937, 0.5010957 , 0.25955367],
       [0.83770713, 0.10863812, 0.08919616, 0.40319757]])

In [11]:
b = a.reshape(1,12)
b

array([[0.69032376, 0.92725569, 0.23165573, 0.88976584, 0.90471173,
        0.94026937, 0.5010957 , 0.25955367, 0.83770713, 0.10863812,
        0.08919616, 0.40319757]])

In [15]:
np.size(b), np.size(a)

(12, 12)

6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [18]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [19]:
b = np.arange(20, 1 , -2)
b

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

Ничем не отличается.

8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [41]:
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [42]:
b = np.ones((3,2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [43]:
np.size(a), np.size(b)

(4, 6)

In [44]:
v = np.vstack((a,b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [45]:
np.size(v)

10

9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [48]:
a = np.arange(0,12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [52]:
A = np.reshape(a, (4,3))
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [54]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [56]:
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [59]:
B.shape

(4, 4)

In [60]:
np.linalg.det(B)

0.0

Определитель матрицы равен нулю - нельзя вычислить обратную матрицу B_inv.

10. Инициализируйте генератор случайных чисел с помощью объекта seed, равного 42.

In [62]:
np.random.seed(42)

11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.

In [67]:
c = np.random.randint(0,16,16)
c

array([ 0, 11,  9,  5, 12, 11,  8,  0, 10, 10, 14,  9, 15, 11, 11, 15])

12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [69]:
C = np.reshape(c, (4,4))
C

array([[ 0, 11,  9,  5],
       [12, 11,  8,  0],
       [10, 10, 14,  9],
       [15, 11, 11, 15]])

In [71]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [72]:
Bx10 = np.dot(B, 10)
Bx10

array([[  50,  140,  230,  320],
       [ 140,  500,  860, 1220],
       [ 230,  860, 1490, 2120],
       [ 320, 1220, 2120, 3020]])

In [73]:
D = Bx10 + C
D

array([[  50,  151,  239,  325],
       [ 152,  511,  868, 1220],
       [ 240,  870, 1504, 2129],
       [ 335, 1231, 2131, 3035]])

In [74]:
np.linalg.matrix_rank(D)

4

In [75]:
np.linalg.det(D)

-1705239.0000000005

In [81]:
D_inv = np.linalg.inv(D)
D_inv

array([[-0.13177214,  0.18751155, -0.07784833, -0.00665537],
       [ 0.18065034, -0.13360884, -0.04707844,  0.06738762],
       [-0.05583792, -0.00799595,  0.18536698, -0.12083819],
       [-0.01952102,  0.03910889, -0.10246599,  0.05857713]])


13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4. Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [86]:
D_inv = [['0' if num < 0 else '1' for num in line] for line in D_inv]
D_inv

[['0', '1', '0', '0'],
 ['1', '0', '0', '1'],
 ['0', '0', '1', '0'],
 ['0', '1', '0', '1']]

In [89]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [90]:
C

array([[ 0, 11,  9,  5],
       [12, 11,  8,  0],
       [10, 10, 14,  9],
       [15, 11, 11, 15]])

In [92]:
E = np.where(D_inv, B, C)
E

array([[  0,  14,   9,   5],
       [ 14,  11,   8, 122],
       [ 10,  10, 149,   9],
       [ 15, 122,  11, 302]])